name: bip39_multi
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.7
homepage: https://github.com/anicdh/bip39

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: ^3.4.0
  hex: ^0.2.0
  crypto: ^3.0.0
dev_dependencies:
  test: ^1.0.0
