name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.0
homepage: https://github.com/anicdh/bip39
author: anicdh <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  resource: ^2.1.5
  pointycastle: ^1.0.0-rc2
  hex: ^0.1.2
  crypto: ^2.0.6
dev_dependencies:
  test: ^1.0.0
